char* caesar_cipher(char* text, int shift);
int caesar_cipher_main();
void demo_strtok(void);
int variadic_sum(int num_args, ...);
int demo_variadic_sum(void);
int eulers_method_main();
int newtons_method_main();
void demo_print_stuff_on_one_line();
void read_file (char *filename, char **ret_char_array, int *ret_char_length);
static void print_char(unsigned char theChar);
int read_file_main();
void sprint_float3(char* str, float arg);
int sprint_float3_main();
void* add1_to_global(void* arg);
void thread_race_main();
double time_elapsed();
int demo_cpp_vectors();