# CC = g++ $@.cpp -o $@ -Iinclude -framework SDL2 -framework SDL2_image -framework SDL2_mixer -framework SDL2_net -framework SDL2_ttf

all: 
	sh make.sh

# clean: 
# 	rm first show_images

# first:
# 	$(CC)

# show_images:
# 	$(CC)

# render_text:
# 	$(CC)
